[
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2954",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2954/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2954/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2954/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2954",
    "id": 18780951,
    "number": 2954,
    "title": "opencon thread massively slows down client shutdown?",
    "user": {
      "login": "Diapolo",
      "id": 1419649,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1419649?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Diapolo",
      "html_url": "https://github.com/Diapolo",
      "followers_url": "https://api.github.com/users/Diapolo/followers",
      "following_url": "https://api.github.com/users/Diapolo/following{/other_user}",
      "gists_url": "https://api.github.com/users/Diapolo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Diapolo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Diapolo/subscriptions",
      "organizations_url": "https://api.github.com/users/Diapolo/orgs",
      "repos_url": "https://api.github.com/users/Diapolo/repos",
      "events_url": "https://api.github.com/users/Diapolo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Diapolo/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 12,
    "created_at": "2013-08-30T10:29:12Z",
    "updated_at": "2014-09-15T15:29:09Z",
    "closed_at": "2014-09-15T15:29:09Z",
    "author_association": "NONE",
    "body": "This is with latest 0.8.4 RC on Win7 x64, I have no idea yet what causes this, but I'm sure shutdown with previous versions was faster. This was with proxy enabled, problem seems to be non existant with proxy disabled.\n\n@sipa Any idea for such a behaviour? Any timeout blocking that thread?\n\nProxy enabled (opencon takes 1 1/2 minutes to interrupt):\n\n<pre>\n2013-08-30 10:25:25 addcon thread interrupt\n2013-08-30 10:25:25 net thread interrupt\n2013-08-30 10:25:25 dumpaddr thread stop\n2013-08-30 10:25:25 msghand thread interrupt\n2013-08-30 10:27:04 opencon thread interrupt\n2013-08-30 10:27:04 Flush(false)\n2013-08-30 10:27:04 wallet.dat refcount=0\n2013-08-30 10:27:04 wallet.dat checkpoint\n2013-08-30 10:27:04 wallet.dat detach\n2013-08-30 10:27:04 wallet.dat closed\n2013-08-30 10:27:04 DBFlush(false) ended              47ms\n2013-08-30 10:27:04 StopNode()\n2013-08-30 10:27:04 Flushed 14694 addresses to peers.dat  47ms\n2013-08-30 10:27:04 Committing 30072 changed transactions to coin database...\n2013-08-30 10:27:05 Flush(true)\n2013-08-30 10:27:05 wallet.dat refcount=0\n2013-08-30 10:27:05 wallet.dat checkpoint\n2013-08-30 10:27:05 wallet.dat detach\n2013-08-30 10:27:05 wallet.dat closed\n2013-08-30 10:27:05 DBFlush(true) ended              16ms\n</pre>\n\n\nProxy disabled (opencon immediately interrupted):\n<per>\n2013-08-30 10:31:26 addcon thread interrupt\n2013-08-30 10:31:26 dumpaddr thread stop\n2013-08-30 10:31:26 net thread interrupt\n2013-08-30 10:31:26 msghand thread interrupt\n2013-08-30 10:31:29 connection timeout\n2013-08-30 10:31:29 opencon thread interrupt\n2013-08-30 10:31:29 Flush(false)\n2013-08-30 10:31:29 wallet.dat refcount=0\n2013-08-30 10:31:29 wallet.dat checkpoint\n2013-08-30 10:31:29 wallet.dat detach\n2013-08-30 10:31:30 wallet.dat closed\n2013-08-30 10:31:30 DBFlush(false) ended              42ms\n2013-08-30 10:31:30 StopNode()\n2013-08-30 10:31:30 Flushed 14542 addresses to peers.dat  68ms\n2013-08-30 10:31:30 Committing 542 changed transactions to coin database...\n2013-08-30 10:31:30 Flush(true)\n2013-08-30 10:31:30 wallet.dat refcount=0\n2013-08-30 10:31:30 wallet.dat checkpoint\n2013-08-30 10:31:30 wallet.dat detach\n2013-08-30 10:31:30 wallet.dat closed\n2013-08-30 10:31:30 DBFlush(true) ended              20ms\n</pre>\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2927",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2927/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2927/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2927/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2927",
    "id": 18481455,
    "number": 2927,
    "title": "UPNP is not disabled when tor-only settings are in effect. ",
    "user": {
      "login": "ghost",
      "id": 10137,
      "avatar_url": "https://avatars3.githubusercontent.com/u/10137?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ghost",
      "html_url": "https://github.com/ghost",
      "followers_url": "https://api.github.com/users/ghost/followers",
      "following_url": "https://api.github.com/users/ghost/following{/other_user}",
      "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
      "organizations_url": "https://api.github.com/users/ghost/orgs",
      "repos_url": "https://api.github.com/users/ghost/repos",
      "events_url": "https://api.github.com/users/ghost/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ghost/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 14,
    "created_at": "2013-08-23T17:12:11Z",
    "updated_at": "2015-05-27T07:33:12Z",
    "closed_at": "2015-05-27T07:33:12Z",
    "author_association": "NONE",
    "body": "With the following enabled, UPNP _should not_ attempt to open a port at the router for 8333, however in the latest stable the port is uselessly opened. At best it's doing nothing productive, at worst it's just advertising the existence of a bitcoin client. \n\n```\nonlynet=tor\ntor=127.0.0.1:9050\ndiscover=0\nlisten=0\n```\n\nCompiling with USE_UPNP=- works as a temporary solution, but is by no means ideal. \n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2889",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2889/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2889/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2889/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2889",
    "id": 17889252,
    "number": 2889,
    "title": "Rapidly getting blocks via RPC causes bitcoind to temporarily stop responding to RPC commands",
    "user": {
      "login": "ryanxcharles",
      "id": 63740,
      "avatar_url": "https://avatars3.githubusercontent.com/u/63740?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ryanxcharles",
      "html_url": "https://github.com/ryanxcharles",
      "followers_url": "https://api.github.com/users/ryanxcharles/followers",
      "following_url": "https://api.github.com/users/ryanxcharles/following{/other_user}",
      "gists_url": "https://api.github.com/users/ryanxcharles/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ryanxcharles/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ryanxcharles/subscriptions",
      "organizations_url": "https://api.github.com/users/ryanxcharles/orgs",
      "repos_url": "https://api.github.com/users/ryanxcharles/repos",
      "events_url": "https://api.github.com/users/ryanxcharles/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ryanxcharles/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 98279177,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/RPC/REST/ZMQ",
        "name": "RPC/REST/ZMQ",
        "color": "0052cc",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 17,
    "created_at": "2013-08-09T22:57:28Z",
    "updated_at": "2018-01-22T13:49:04Z",
    "closed_at": "2016-04-28T11:19:41Z",
    "author_association": "CONTRIBUTOR",
    "body": "When retrieving blocks from the blockchain using bitcoind RPC commands, bitcoind will temporarily stop sending responses to RPC commands after many thousands of commands if the commands are sent in quick succession. The issue has something to do with timing, since adding a delay to retrieving blocks will make the problem go away.\n\nThis node.js code will display the issue (obviously, replace \"password\" with your bitcoind password):\n\n``` javascript\nvar rpc=require('json-rpc2');\nvar bitcoind=rpc.Client.create(8332, \"localhost\",\n  \"bitcoinrpc\", \"password\");\nvar chain=function(blockhash){\n  bitcoind.call('getblock',[blockhash],function(err,block){\n    if (err){\n      console.log(String(err));\n      if (String(err)==\"Error: Have no response object\"){\n        console.log(\"Thought so.\");\n      }\n      return;\n    }\n    console.log(block.hash, block.height);\n    if (block.nextblockhash){\n      chain(block.nextblockhash);\n    };\n  });\n};\nchain(\"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f\");\n```\n\nNote that my development machine has an SSD, and so blocks are retrieved quickly by bitcoind - it may be necessary to use an SSD to reproduce the problem.\n\nWhat this code does is to retrieve the genesis block, then get the next block, and the next block, and so on, until it has got all the blocks. Except at around 25,000 or so blocks in (different every time), it will quit when it encounters a \"no response object\" error. This error has nothing to do with node.js or json-rpc2 - it is a bitcoind error. This can be seen by running bitcoin commands from the command prompt, which result in a \"couldn't connect to server\" error, e.g.:\n\n```\n> bitcoind getblock 00000000722ecede1cc4edd52a7d416bdafd6528f630926b0021b41a6b57ba5d\nerror: couldn't connect to server\n```\n\nAfter a few seconds, bitcoind will begin responding to commads again. It doesn't crash. It just stops responding to commands for a short while.\n\nBy delaying repeated RPC commands, the above code can be fixed to run without freezing bitcoind (notice the 10ms setTimeout):\n\n``` javascript\nvar rpc=require('json-rpc2');\nvar bitcoind=rpc.Client.create(8332, \"localhost\",\n  \"bitcoinrpc\", \"password\");\nvar chain=function(blockhash){\n  bitcoind.call('getblock',[blockhash],function(err,block){\n    if (err){\n      console.log(String(err));\n      if (String(err)==\"Error: Have no response object\"){\n        console.log(\"Thought so.\");\n      }\n      return;\n    }\n    console.log(block.hash, block.height);\n    if (block.nextblockhash){\n      setTimeout(function(){\n        chain(block.nextblockhash);\n      },10);\n    };\n  });\n};\nchain(\"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f\");\n```\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2887",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2887/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2887/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2887/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2887",
    "id": 17810231,
    "number": 2887,
    "title": "Invalid behavior of the \"Connect through SOCKS proxy\" checkbox",
    "user": {
      "login": "VirtualDestructor",
      "id": 3777960,
      "avatar_url": "https://avatars1.githubusercontent.com/u/3777960?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/VirtualDestructor",
      "html_url": "https://github.com/VirtualDestructor",
      "followers_url": "https://api.github.com/users/VirtualDestructor/followers",
      "following_url": "https://api.github.com/users/VirtualDestructor/following{/other_user}",
      "gists_url": "https://api.github.com/users/VirtualDestructor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/VirtualDestructor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/VirtualDestructor/subscriptions",
      "organizations_url": "https://api.github.com/users/VirtualDestructor/orgs",
      "repos_url": "https://api.github.com/users/VirtualDestructor/repos",
      "events_url": "https://api.github.com/users/VirtualDestructor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/VirtualDestructor/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 135946,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/GUI",
        "name": "GUI",
        "color": "02d7e1",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2013-08-08T14:42:47Z",
    "updated_at": "2014-01-17T12:25:39Z",
    "closed_at": "2014-01-17T12:25:39Z",
    "author_association": "NONE",
    "body": "Steps to reproduce:\n1. Run Bitcoin-Qt with limited NET_IPV4. (for ex. with the \"-onlynet=tor\" option).\n2. Go to Options-Network.\n3. Check the \"Connect through SOCKS proxy\" checkbox and press Apply.\n4. The checkbox becomes unchecked, but the option \"fUseProxy\" in the qt-settings file (~/.config/Bitcoin/Bitcoin-Qt.conf) now has value \"true\".\n5. Restart Bitcoin-Qt without any limitations (without options).\n6. Go to Options-Network.\n7. The checkbox is checked (because \"fUseProxy=true\").\n8. Try to uncheck it, but it becomes checked again after pressing Apply. There is no way to uncheck it now.\n\nThe same behavior appears under Windows too.\n\nI guess the problem caused by this line https://github.com/bitcoin/bitcoin/blob/0.8.3/src/qt/optionsmodel.cpp#L168\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2846",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2846/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2846/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2846/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2846",
    "id": 17082681,
    "number": 2846,
    "title": "Listunspent does not return proper set of transactions",
    "user": {
      "login": "ThePiachu",
      "id": 964559,
      "avatar_url": "https://avatars0.githubusercontent.com/u/964559?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ThePiachu",
      "html_url": "https://github.com/ThePiachu",
      "followers_url": "https://api.github.com/users/ThePiachu/followers",
      "following_url": "https://api.github.com/users/ThePiachu/following{/other_user}",
      "gists_url": "https://api.github.com/users/ThePiachu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ThePiachu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ThePiachu/subscriptions",
      "organizations_url": "https://api.github.com/users/ThePiachu/orgs",
      "repos_url": "https://api.github.com/users/ThePiachu/repos",
      "events_url": "https://api.github.com/users/ThePiachu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ThePiachu/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 149424,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Wallet",
        "name": "Wallet",
        "color": "08a781",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2013-07-23T03:38:48Z",
    "updated_at": "2018-03-07T14:51:31Z",
    "closed_at": "2018-03-07T14:51:30Z",
    "author_association": "NONE",
    "body": "I ran into issue with listunspent API call. \n\ngetaddressesbyaccount(\"account\") returns ['n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'] - my account has only 1 address.\n\nI call getbalance(\"account\", 6), I get a value of 2203.46345285 - I have 2K testnet Bitcoins in that address, that looks like a plenty of transactions to spent. \n\nI call listunspent(1, 999999, [\"n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe\"]) and get [] - nothing.\n\nI did not use \"move\" command, just a lot of non-standard calls for creating new transactions and sending them (createraw, signraw, sendraw).\n\nI check BTCLook and see plenty of unspent transactions - http://testnet.btclook.com/addr/n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe .\n\nSimilarly, calling listtransactions(\"Holding\", 10, 0) returns:\n\n[\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':56,\n      'time':1374478540,\n      'txid':'1941fd5935391114ed63a0ac1bd346b95f97730be8c33c1077b95cea39246006',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478540,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':51,\n      'time':1374478542,\n      'txid':'0785d7b2ffc886deec34b31abdd4e25dff087d188a36384962536258c36096e0',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478542,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':58,\n      'time':1374478543,\n      'txid':'df46e6639cbe58ba6e68edf89b9bd1ea0ebf1736902fe6a844efac6aeabc100f',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478543,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':60,\n      'time':1374478544,\n      'txid':'0446b87eee83469d91b102c0cc39cef71f403a07e20997af0ce28371b3b9356c',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478544,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':44,\n      'time':1374478545,\n      'txid':'6efbbd3fa826d23cece4107b2de6fc16b30792b261a5971974d63ee7ac35bd66',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478545,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':62,\n      'time':1374478547,\n      'txid':'c398670415396795ef8d5a1577268d948d707d680679a70bdf00175f221ed6b3',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478547,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':64,\n      'time':1374478548,\n      'txid':'acd1fb20bffc40e40da52256c53d3093429e5d19cc2682764a31c83818e9ad59',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478548,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':17,\n      'time':1374478549,\n      'txid':'dd0edeaa84267baad818f127836ed8b4892a70f9a5bb99d9479cd4fb062c5a0b',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478549,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',\n      'blockindex':18,\n      'time':1374478550,\n      'txid':'584973a9f5ebb987311323f65786279c64fa000e9fdc371dbbcbc089a77dbb51',\n      'blocktime':1374478752,\n      'amount':0.09989999,\n      'confirmations':92,\n      'timereceived':1374478550,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   },\n   {\n      'category':'receive',\n      'account':'Holding',\n      'time':1374549589,\n      'txid':'a8c18f467d960e7304b77bc428e6e06308628c6d3ab777ec425d503561228108',\n      'amount':99.99980234,\n      'confirmations':0,\n      'timereceived':1374549589,\n      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'\n   }\n]\n\nThis is why I think that there is some bug in listunspent that makes this API call not return proper values.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2838",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2838/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2838/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2838/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2838",
    "id": 17005259,
    "number": 2838,
    "title": "Timing leak in RPC authentication",
    "user": {
      "login": "pakt",
      "id": 873464,
      "avatar_url": "https://avatars3.githubusercontent.com/u/873464?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pakt",
      "html_url": "https://github.com/pakt",
      "followers_url": "https://api.github.com/users/pakt/followers",
      "following_url": "https://api.github.com/users/pakt/following{/other_user}",
      "gists_url": "https://api.github.com/users/pakt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pakt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pakt/subscriptions",
      "organizations_url": "https://api.github.com/users/pakt/orgs",
      "repos_url": "https://api.github.com/users/pakt/repos",
      "events_url": "https://api.github.com/users/pakt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pakt/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 4,
    "created_at": "2013-07-20T11:10:47Z",
    "updated_at": "2013-11-12T14:24:37Z",
    "closed_at": "2013-11-12T14:24:37Z",
    "author_association": "NONE",
    "body": "`bitcoinrpc.cpp`\n\n``` c++\n\nbool HTTPAuthorized(map<string, string>& mapHeaders)\n{\n    string strAuth = mapHeaders[\"authorization\"];\n    if (strAuth.substr(0,6) != \"Basic \")\n        return false;\n    string strUserPass64 = strAuth.substr(6); boost::trim(strUserPass64);\n    string strUserPass = DecodeBase64(strUserPass64);\n    return strUserPass == strRPCUserColonPass;\n}\n```\n\nLast string comparision `strUserPass == strRPCUserColonPass` gets compiled to:\n\n```\n    do\n    {\n      if ( !len )\n        break;\n      less = *(_BYTE *)strUserPass < *(_BYTE *)strRPCUserColonPass;\n      eq = *(_BYTE *)strUserPass++ == *(_BYTE *)strRPCUserColonPass++;\n      --len;\n    }\n    while ( eq );\n```\n\nwhich is a byte-by-byte compare. Attacker with precise clock (being in the same LAN, for example) might learn the RPC password letter by letter, by trying passwords like 'a...\", \"b...\", \"c...\" and observing which took the longest time to verify.\n\nThis code in `bitcoinrpc.cpp`:\n\n``` c++\n            if (mapArgs[\"-rpcpassword\"].size() < 20)\n                MilliSleep(250);\n```\n\nprotects from bruteforce for short password. Unfortunately, when run, bitcoind suggest a 32 chars password. Paradoxically short passwords are safer to use than longer ones, wrt to the timing leak.\n\nHere's an example of time independent array comparison: http://rdist.root.org/2010/01/07/timing-independent-array-comparison/\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2821",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2821/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2821/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2821/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2821",
    "id": 16593382,
    "number": 2821,
    "title": "Assertion mempool transaction missing input",
    "user": {
      "login": "Krellan",
      "id": 4563817,
      "avatar_url": "https://avatars2.githubusercontent.com/u/4563817?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Krellan",
      "html_url": "https://github.com/Krellan",
      "followers_url": "https://api.github.com/users/Krellan/followers",
      "following_url": "https://api.github.com/users/Krellan/following{/other_user}",
      "gists_url": "https://api.github.com/users/Krellan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Krellan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Krellan/subscriptions",
      "organizations_url": "https://api.github.com/users/Krellan/orgs",
      "repos_url": "https://api.github.com/users/Krellan/repos",
      "events_url": "https://api.github.com/users/Krellan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Krellan/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2013-07-10T18:40:01Z",
    "updated_at": "2016-02-16T17:27:57Z",
    "closed_at": "2016-02-16T17:27:57Z",
    "author_association": "CONTRIBUTOR",
    "body": "This seems similar to Issue #2570 even though that is closed.  Interestingly, it still happens in the bitcoin-qt 0.8.3 client, v0.8.3.0-g40809ae-beta version.\n\nThis was a clean compile from source, running on Gentoo Linux (64-bit).  I compiled this independently of the Gentoo system, so no unusual compiler options or anything like that should have been used.\n\nI believe it also happens during a block reorganization.  Here is the debug log:\n\n```\nsending: addr (31 bytes)\nsending: inv (37 bytes)\nreceived: inv (37 bytes)\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nreceived: addr (31 bytes)\nsending: inv (37 bytes)\nreceived: inv (37 bytes)\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nreceived: inv (37 bytes)\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nsending: inv (73 bytes)\nreceived: inv (37 bytes)\n  got inventory: block 000000000000001aa6707204b2d1887089a860eceaf8a893a7c2d08dfe6ac525  have\nsending: getblocks (965 bytes)\nreceived: inv (73 bytes)\n  got inventory: tx 53b325cd548867df032b8879a18abd9c1b97638b3a3c380c38cd8546626d36c5  have\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nreceived: inv (37 bytes)\n  got inventory: tx 53b325cd548867df032b8879a18abd9c1b97638b3a3c380c38cd8546626d36c5  have\nsending: addr (31 bytes)\nsending: inv (73 bytes)\nreceived: inv (37 bytes)\n  got inventory: block 000000000000000dd0d039cf7c7e006d79a915b0ee76180bb300dc74ed3308a2  new\naskfor block 000000000000000dd0d039cf7c7e006d79a915b0ee76180bb300dc74ed3308a2   1373479424000000 (18:03:44)\nreceived: inv (37 bytes)\n  got inventory: block 000000000000001aa6707204b2d1887089a860eceaf8a893a7c2d08dfe6ac525  have\nsending: getblocks (965 bytes)\nreceived: getblocks (965 bytes)\ngetblocks 194158 to 0000000000000000000000000000000000000000000000000000000000000000 limit 500\n  getblocks stopping at limit 194657 00000000000000a13f6a1b564b6ef5bc06067da0374e181f4acf7f3c4d9caf37\nsending: inv (18003 bytes)\nreceived: inv (73 bytes)\n  got inventory: block 000000000000001aa6707204b2d1887089a860eceaf8a893a7c2d08dfe6ac525  have\nsending: getblocks (965 bytes)\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nreceived: inv (37 bytes)\n  got inventory: block 000000000000001aa6707204b2d1887089a860eceaf8a893a7c2d08dfe6ac525  have\nsending: getblocks (965 bytes)\nreceived: block (101786 bytes)\nreceived block 000000000000000dd0d039cf7c7e006d79a915b0ee76180bb300dc74ed3308a2\nREORGANIZE: Disconnect 1 blocks; 000000000000009fd60babdec39b4e49feb4ec17497c0b341e05beb7e692304a..\nREORGANIZE: Connect 2 blocks; ..000000000000001aa6707204b2d1887089a860eceaf8a893a7c2d08dfe6ac525\nCommitting 2146 changed transactions to coin database...\nERROR: Non-canonical signature: R value negative\nERROR: CScriptCheck() : ac0bed4e30581eecf567e9a96ca7b97e5721532b097250c2eb2a5df2c625ad15 VerifySignature failed\nERROR: CTxMemPool::accept() : ConnectInputs failed ac0bed4e30581eecf567e9a96ca7b97e5721532b097250c2eb2a5df2c625ad15\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: Non-canonical signature: R value negative\nERROR: CScriptCheck() : 8a25c7ea809620294d5562026133e3a94f1a3ca429579f9280485e50853b5546 VerifySignature failed\nERROR: CTxMemPool::accept() : ConnectInputs failed 8a25c7ea809620294d5562026133e3a94f1a3ca429579f9280485e50853b5546\nERROR: Non-canonical signature: R value negative\nERROR: CScriptCheck() : 5d8bbdfa6f215f7b33bfcb9608e5e6dd739cc563daf0fc0c591edfd73a8d17ae VerifySignature failed\nERROR: CTxMemPool::accept() : ConnectInputs failed 5d8bbdfa6f215f7b33bfcb9608e5e6dd739cc563daf0fc0c591edfd73a8d17ae\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: CTxMemPool::accept() : inputs already spent\nERROR: Non-canonical signature: S value negative\nERROR: CScriptCheck() : 3b33366cf854d9046678fffadde8dac3435431a33c217ee1a25826502a3ef569 VerifySignature failed\nERROR: CTxMemPool::accept() : ConnectInputs failed 3b33366cf854d9046678fffadde8dac3435431a33c217ee1a25826502a3ef569\nCTxMemPool::accept() : accepted cc4668b4f417e12492b384d22e081843da52875ecb072f2c39efc982a9fa9a4e (poolsz 1304)\nSetBestChain: new best=000000000000001aa6707204b2d1887089a860eceaf8a893a7c2d08dfe6ac525  height=245886  log2_work=70.667529  tx=20513801  date=2013-07-10 17:47:29 progress=0.999999\nProcessBlock: ACCEPTED\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nreceived: inv (37 bytes)\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nreceived: inv (37 bytes)\n  got inventory: block 000000000000000dd0d039cf7c7e006d79a915b0ee76180bb300dc74ed3308a2  have\nsending: getblocks (965 bytes)\nforce request: block 000000000000000dd0d039cf7c7e006d79a915b0ee76180bb300dc74ed3308a2\nsending: inv (37 bytes)\nsending: inv (73 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nreceived: inv (37 bytes)\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nsending getdata: tx 86a417868917ef04aa7762df4e9d8e8e2d289000e269ebd60787a92f1ab50b25\nsending: getdata (37 bytes)\nsending: inv (37 bytes)\nsending: block (248889 bytes)\nsending: block (98904 bytes)\nsending: block (113210 bytes)\nsending: block (77749 bytes)\nsending: block (63716 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nsending: inv (37 bytes)\nreceived: inv (37 bytes)\n  got inventory: tx 0a740a5544620f9b89bb14abf077f8624835bbb5ee65e45f319f9c3e5f8ee6c8  have\nsending: inv (37 bytes)\nreceived: inv (37 bytes)\n  got inventory: block 000000000000000dd0d039cf7c7e006d79a915b0ee76180bb300dc74ed3308a2  have\nsending: getblocks (965 bytes)\nforce request: block 000000000000000dd0d039cf7c7e006d79a915b0ee76180bb300dc74ed3308a2\nERROR: mempool transaction missing input\nbitcoin-qt: src/main.cpp:4251: CBlockTemplate* CreateNewBlock(CReserveKey&): Assertion `\"mempool transaction missing input\" == 0' failed.\n```\n\nAfter this, I restarted the client again, and it came right back up and running without incident.\n\nJosh\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2785",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2785/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2785/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2785/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2785",
    "id": 15893274,
    "number": 2785,
    "title": "ChainState DB uncorrupted itself",
    "user": {
      "login": "fanquake",
      "id": 863730,
      "avatar_url": "https://avatars2.githubusercontent.com/u/863730?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fanquake",
      "html_url": "https://github.com/fanquake",
      "followers_url": "https://api.github.com/users/fanquake/followers",
      "following_url": "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url": "https://api.github.com/users/fanquake/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
      "organizations_url": "https://api.github.com/users/fanquake/orgs",
      "repos_url": "https://api.github.com/users/fanquake/repos",
      "events_url": "https://api.github.com/users/fanquake/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fanquake/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 234879,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/MacOSX",
        "name": "MacOSX",
        "color": "660000",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 11,
    "created_at": "2013-06-23T05:02:16Z",
    "updated_at": "2015-06-13T12:07:34Z",
    "closed_at": "2014-01-17T12:28:27Z",
    "author_association": "MEMBER",
    "body": "Running 0.8.2-beta on OSX 10.8.4\n\nOpened Qt to a corrupted chainstate, and was told to rebuild. Decided to do it later, so chose abort from the popup. \n\nOpened Qt the next day to no corruption message, and it's just syncing per normal.\n\nThis debug snippet below is from the shutdown before corruption, opening the corrupted wallet and choosing to not rebuild and finally opening the wallet and having it load successfully.\n\nAdded 1 addresses from 173.197.107.3: 683 tried, 13640 new\nreceived getdata for: tx a535a410388497f78b4bb77b9c929242d6174b0d26f396cc10212d9dcfafb95e\nCTxMemPool::accept() : accepted e3406befa1868f30485c44a460586ec374186b3ce07e1c287b6afdbb44a8909f (poolsz 1451)\nreceived getdata for: tx e3406befa1868f30485c44a460586ec374186b3ce07e1c287b6afdbb44a8909f\nreceived getdata for: tx e3406befa1868f30485c44a460586ec374186b3ce07e1c287b6afdbb44a8909f\nFlushed 14323 addresses to peers.dat  24ms\nAdded 1 addresses from 173.197.107.3: 683 tried, 13640 new\nreceived getdata for: tx 8a7b68238126e3a167f8d4369bc1b5c832147e6b3aa5a291b2af462f2a4b51ff\ndumpaddr thread stop\nmsghand thread interrupt\nopencon thread interrupt\nnet thread interrupt\naddcon thread interrupt\nFlush(false)\nDBFlush(false) ended               0ms\nStopNode()\nUPNP_DeletePortMapping() returned : 0\nupnp thread interrupt\nFlushed 14322 addresses to peers.dat  25ms\nCommitting 775 changed transactions to coin database...\nFlush(true)\nwallet.dat refcount=0\nwallet.dat checkpoint\nwallet.dat detach\nwallet.dat closed\nDBFlush(true) ended              67ms\n\nBitcoin version v0.8.2-beta (2013-05-25 08:48:25 -0700)\nUsing OpenSSL version OpenSSL 1.0.1c 10 May 2012\nStartup time: 2013-06-22 15:18:30\nDefault data directory /Users/xxxx/Library/Application Support/Bitcoin\nUsing data directory /Users/xxxx/Library/Application Support/Bitcoin\nUsing at most 125 connections (2560 file descriptors available)\nUsing 8 threads for script verification\ninit message: Verifying wallet...\ndbenv.open LogDir=/Users/xxxx/Library/Application Support/Bitcoin/database ErrorFile=/Users/xxxx/Library/Application Support/Bitcoin/db.log\nBound to [::]:8333\nBound to 0.0.0.0:8333\ninit message: Loading block index...\nOpening LevelDB in /Users/xxxx/Library/Application Support/Bitcoin/blocks/index\nOpened LevelDB successfully\nOpening LevelDB in /Users/xxxx/Library/Application Support/Bitcoin/chainstate\nOpened LevelDB successfully\nLoadBlockIndexDB(): last block file = 67\nLoadBlockIndexDB(): last block file info: CBlockFileInfo(blocks=175, size=28716039, heights=242380...242554, time=2013-06-20...2013-06-21)\nLoadBlockIndexDB(): transaction index disabled\nLoadBlockIndexDB(): hashBestChain=00000000000000241476e0d024a206a2e8555a97f0fc0b5ab522d492b5dab34f  height=242554 date=2013-06-21 06:54:39\ninit message: Verifying blocks...\nVerifying last 288 blocks at level 3\nLevelDB read failure: Corruption: block checksum mismatch\nFlush(false)\nDBFlush(false) ended               0ms\nStopNode()\nFlushed 0 addresses to peers.dat  1ms\nCommitting 8 changed transactions to coin database...\nFlush(true)\nDBFlush(true) ended               0ms\n\nBitcoin version v0.8.2-beta (2013-05-25 08:48:25 -0700)\nUsing OpenSSL version OpenSSL 1.0.1c 10 May 2012\nStartup time: 2013-06-23 04:32:54\nDefault data directory /Users/xxxx/Library/Application Support/Bitcoin\nUsing data directory /Users/xxxx/Library/Application Support/Bitcoin\nUsing at most 125 connections (2560 file descriptors available)\nUsing 8 threads for script verification\ninit message: Verifying wallet...\ndbenv.open LogDir=/Users/xxxx/Library/Application Support/Bitcoin/database ErrorFile=/Users/xxxx/Library/Application Support/Bitcoin/db.log\nBound to [::]:8333\nBound to 0.0.0.0:8333\ninit message: Loading block index...\nOpening LevelDB in /Users/xxxx/Library/Application Support/Bitcoin/blocks/index\nOpened LevelDB successfully\nOpening LevelDB in /Users/xxxx/Library/Application Support/Bitcoin/chainstate\nOpened LevelDB successfully\nLoadBlockIndexDB(): last block file = 67\nLoadBlockIndexDB(): last block file info: CBlockFileInfo(blocks=175, size=28716039, heights=242380...242554, time=2013-06-20...2013-06-21)\nLoadBlockIndexDB(): transaction index disabled\nLoadBlockIndexDB(): hashBestChain=00000000000000241476e0d024a206a2e8555a97f0fc0b5ab522d492b5dab34f  height=242554 date=2013-06-21 06:54:39\ninit message: Verifying blocks...\nVerifying last 288 blocks at level 3\nNo coin database inconsistencies in last 150 blocks (53329 transactions)\n block index           17768ms\ninit message: Loading wallet...\nnFileVersion = 80202\n wallet                 1171ms\ninit message: Loading addresses...\nLoaded 0 addresses from peers.dat  1ms\nmapBlockIndex.size() = 242556\nnBestHeight = 242554\nsetKeyPool.size() = 100\nmapWallet.size() = 19\nmapAddressBook.size() = 24\ndnsseed thread start\nupnp thread start\nLoading addresses from DNS seeds (could take a while)\nnet thread start\naddcon thread start\nopencon thread start\nmsghand thread start\ndumpaddr thread start\nFlushed 0 addresses to peers.dat  1ms\ninit message: Done loading\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2779",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2779/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2779/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2779/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2779",
    "id": 15761942,
    "number": 2779,
    "title": "Wallet encryption is broken!",
    "user": {
      "login": "richardassar",
      "id": 868396,
      "avatar_url": "https://avatars1.githubusercontent.com/u/868396?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/richardassar",
      "html_url": "https://github.com/richardassar",
      "followers_url": "https://api.github.com/users/richardassar/followers",
      "following_url": "https://api.github.com/users/richardassar/following{/other_user}",
      "gists_url": "https://api.github.com/users/richardassar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/richardassar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/richardassar/subscriptions",
      "organizations_url": "https://api.github.com/users/richardassar/orgs",
      "repos_url": "https://api.github.com/users/richardassar/repos",
      "events_url": "https://api.github.com/users/richardassar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/richardassar/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 7,
    "created_at": "2013-06-19T18:57:43Z",
    "updated_at": "2013-11-16T02:25:58Z",
    "closed_at": "2013-06-22T13:46:36Z",
    "author_association": "NONE",
    "body": "Fresh build of bitcoind, fresh wallet.\n- ran `./bitcoind encryptwallet ......`\n- restarted bitcoind\n- ran `./bitcoind walletpassphrase ....`\n- received `error: {\"code\":-15,\"message\":\"Error: running with an unencrypted wallet, but walletpassphrase was called.\"}`\n\nAlso can `dumpprivkey` without unlocking the wallet.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2777",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2777/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2777/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2777/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2777",
    "id": 15752497,
    "number": 2777,
    "title": "shutdown throws lock error",
    "user": {
      "login": "jgarzik",
      "id": 494411,
      "avatar_url": "https://avatars2.githubusercontent.com/u/494411?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jgarzik",
      "html_url": "https://github.com/jgarzik",
      "followers_url": "https://api.github.com/users/jgarzik/followers",
      "following_url": "https://api.github.com/users/jgarzik/following{/other_user}",
      "gists_url": "https://api.github.com/users/jgarzik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jgarzik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jgarzik/subscriptions",
      "organizations_url": "https://api.github.com/users/jgarzik/orgs",
      "repos_url": "https://api.github.com/users/jgarzik/repos",
      "events_url": "https://api.github.com/users/jgarzik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jgarzik/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2013-06-19T15:51:23Z",
    "updated_at": "2015-05-16T07:40:33Z",
    "closed_at": "2015-05-16T07:40:33Z",
    "author_association": "CONTRIBUTOR",
    "body": "During a short run (start, network sync, stop) of bitcoind on Linux Ubuntu 13, this was thrown on the console,\n\n```\nterminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'\n  what():  boost::lock_error\n```\n\nAnd this is the last few lines of the debug log,\n\n```\n2013-06-19 15:47:55 trying connection 190.2.27.221:8333 lastseen=4.7hrs\n2013-06-19 15:47:55 CTxMemPool::accept() : accepted 254d03e64db83bb0ad17e8435f4c5a7932028305789c30642fafb52f6ca20b2a (poolsz 30)\n2013-06-19 15:47:57 received getdata (2 invsz)\n2013-06-19 15:47:59 ThreadRPCServer method=stop\n2013-06-19 15:47:59 addcon thread interrupt\n2013-06-19 15:47:59 dumpaddr thread stop\n2013-06-19 15:47:59 msghand thread interrupt\n2013-06-19 15:47:59 Flush(false)\n2013-06-19 15:47:59 wallet.dat refcount=0\n2013-06-19 15:47:59 wallet.dat checkpoint\n2013-06-19 15:47:59 wallet.dat detach\n2013-06-19 15:47:59 wallet.dat closed\n2013-06-19 15:47:59 DBFlush(false) ended              10ms\n2013-06-19 15:47:59 StopNode()\n2013-06-19 15:47:59 net thread interrupt\n2013-06-19 15:47:59 Flushed 14271 addresses to peers.dat  35ms\n2013-06-19 15:47:59 Committing 33219 changed transactions to coin database...\n2013-06-19 15:48:00 Flush(true)\n2013-06-19 15:48:00 wallet.dat refcount=0\n2013-06-19 15:48:00 wallet.dat checkpoint\n2013-06-19 15:48:00 wallet.dat detach\n2013-06-19 15:48:00 wallet.dat closed\n2013-06-19 15:48:00 DBFlush(true) ended               7ms\n2013-06-19 15:48:00 connection timeout\n```\n\nThe connection timeout following DBFlush seems unusual.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2773",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2773/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2773/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2773/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2773",
    "id": 15633874,
    "number": 2773,
    "title": "Pull request 2763 / Problems bitcoin over Tor",
    "user": {
      "login": "Delta1977",
      "id": 1581154,
      "avatar_url": "https://avatars2.githubusercontent.com/u/1581154?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Delta1977",
      "html_url": "https://github.com/Delta1977",
      "followers_url": "https://api.github.com/users/Delta1977/followers",
      "following_url": "https://api.github.com/users/Delta1977/following{/other_user}",
      "gists_url": "https://api.github.com/users/Delta1977/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Delta1977/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Delta1977/subscriptions",
      "organizations_url": "https://api.github.com/users/Delta1977/orgs",
      "repos_url": "https://api.github.com/users/Delta1977/repos",
      "events_url": "https://api.github.com/users/Delta1977/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Delta1977/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 6,
    "created_at": "2013-06-17T14:02:46Z",
    "updated_at": "2014-01-17T12:30:26Z",
    "closed_at": "2014-01-17T12:30:26Z",
    "author_association": "CONTRIBUTOR",
    "body": "after that Pull Request this Problem occours,\nReverting it, and all is o.k. \n\ndisconnecting node 127.0.0.1:36934\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\naccepted connection 127.0.0.1:36935\nsend version message: version 70001, blocks=242009, us=96.47.226.21:8333, them=0.0.0.0:0, peer=127.0.0.1:36935\nreceive version message: version 32200, blocks=0, us=127.0.0.1:8333, them=127.0.0.1:36935, peer=127.0.0.1:36935\nsocket recv error 104\ndisconnecting node 127.0.0.1:36935\nERROR: CTxMemPool::accept() : nonstandard transaction type\naccepted connection 127.0.0.1:36936\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nsend version message: version 70001, blocks=242009, us=96.47.226.21:8333, them=0.0.0.0:0, peer=127.0.0.1:36936\nreceive version message: version 32200, blocks=0, us=127.0.0.1:8333, them=127.0.0.1:36936, peer=127.0.0.1:36936\nsocket recv error 104\ndisconnecting node 127.0.0.1:36936\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nAdded 2 addresses from 95.211.41.87: 334 tried, 13996 new\nERROR: CTxMemPool::accept() : nonstandard transaction type\naccepted connection 127.0.0.1:36937\nsend version message: version 70001, blocks=242009, us=96.47.226.21:8333, them=0.0.0.0:0, peer=127.0.0.1:36937\nreceive version message: version 32200, blocks=0, us=127.0.0.1:8333, them=127.0.0.1:36937, peer=127.0.0.1:36937\nsocket recv error 104\ndisconnecting node 127.0.0.1:36937\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\nERROR: CTxMemPool::accept() : nonstandard transaction type\naccepted connection 127.0.0.1:36939\nsend version message: version 70001, blocks=242009, us=96.47.226.21:8333, them=0.0.0.0:0, peer=127.0.0.1:36939\nreceive version message: version 32200, blocks=0, us=127.0.0.1:8333, them=127.0.0.1:36939, peer=127.0.0.1:36939\nsocket recv error 104\ndisconnecting node 127.0.0.1:36939\nprobkles\na\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2770",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2770/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2770/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2770/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2770",
    "id": 15583815,
    "number": 2770,
    "title": "LevelDB corruption with 0.8.x Mac client",
    "user": {
      "login": "toffoo",
      "id": 4701899,
      "avatar_url": "https://avatars0.githubusercontent.com/u/4701899?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/toffoo",
      "html_url": "https://github.com/toffoo",
      "followers_url": "https://api.github.com/users/toffoo/followers",
      "following_url": "https://api.github.com/users/toffoo/following{/other_user}",
      "gists_url": "https://api.github.com/users/toffoo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/toffoo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/toffoo/subscriptions",
      "organizations_url": "https://api.github.com/users/toffoo/orgs",
      "repos_url": "https://api.github.com/users/toffoo/repos",
      "events_url": "https://api.github.com/users/toffoo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/toffoo/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 108,
    "created_at": "2013-06-15T00:27:14Z",
    "updated_at": "2014-11-29T05:21:12Z",
    "closed_at": "2014-01-06T09:10:27Z",
    "author_association": "NONE",
    "body": "I've run bitcoin-qt Mac client on the latest OSX version since 0.3.x thru to 0.7.2 with literally zero problems ever, on essentially this same hardware setup.\n\nSince the 0.8 update and switch to LevelDB none of the three Mac client releases have worked stably for me and I've had to downgrade to 0.7.2 (with the May 15 workaround) to maintain a stable bitcoin wallet.\n\nCurrent setup is: MacBook Pro Retina, OSX 10.8.4, bitcoin-qt 0.8.2\n\nI saw that some of the known corruption issues/bugs were fixed/closed with the 0.8.2 release, so I decided to try the upgrade again.  After re-indexing and working fine for hours at time (much better than 0.8.1 at least) upon restart I get \"Error opening block database. Do you want to rebuild the block database?\" which of course I don't want to do because it takes forever, even on this world's fastest Mac with SSD drive.  This has happened 6 times now, and the interesting line in debug.log is:\n\nVerifying last 288 blocks at level 3\nLevelDB read failure: Corruption: block checksum mismatch\n\nMore details here:\nhttps://bitcointalk.org/index.php?topic=155140.0\n\nDowngrading to 0.7.2 again, please help permanently fix this in the next 0.8.x release.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2745",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2745/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2745/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2745/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2745",
    "id": 15201475,
    "number": 2745,
    "title": "Assertion failed in dbformat.h",
    "user": {
      "login": "grue0",
      "id": 1332097,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1332097?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/grue0",
      "html_url": "https://github.com/grue0",
      "followers_url": "https://api.github.com/users/grue0/followers",
      "following_url": "https://api.github.com/users/grue0/following{/other_user}",
      "gists_url": "https://api.github.com/users/grue0/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/grue0/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/grue0/subscriptions",
      "organizations_url": "https://api.github.com/users/grue0/orgs",
      "repos_url": "https://api.github.com/users/grue0/repos",
      "events_url": "https://api.github.com/users/grue0/events{/privacy}",
      "received_events_url": "https://api.github.com/users/grue0/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 4,
    "created_at": "2013-06-06T00:53:31Z",
    "updated_at": "2014-02-17T14:32:23Z",
    "closed_at": "2014-02-17T14:32:23Z",
    "author_association": "NONE",
    "body": "Assertion failed!\n\nProgram: C:\\Users\\grue\\bitcoin\\bitcoin-qt.exe\nFile: ./db/dbformat.h\nLine: 96\n\nExpression: internal_key.size() >= 8\n\nFor information on how your program can cause an assertion\nfailure, see the Visual C++ documentation on asserts\n\ndebug.log: http://pastie.org/pastes/8012570/text?key=l6vaa5dmndg83uvlrd853q\ndebug.log 2: http://pastie.org/pastes/8012603/text?key=ktehn0ceduoz4sytbqgza\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2739",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2739/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2739/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2739/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2739",
    "id": 15149550,
    "number": 2739,
    "title": "RPC-related hangs on shutdown",
    "user": {
      "login": "jeremysawicki",
      "id": 3847496,
      "avatar_url": "https://avatars0.githubusercontent.com/u/3847496?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jeremysawicki",
      "html_url": "https://github.com/jeremysawicki",
      "followers_url": "https://api.github.com/users/jeremysawicki/followers",
      "following_url": "https://api.github.com/users/jeremysawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/jeremysawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jeremysawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jeremysawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/jeremysawicki/orgs",
      "repos_url": "https://api.github.com/users/jeremysawicki/repos",
      "events_url": "https://api.github.com/users/jeremysawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jeremysawicki/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 98279177,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/RPC/REST/ZMQ",
        "name": "RPC/REST/ZMQ",
        "color": "0052cc",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 3,
    "created_at": "2013-06-05T01:14:53Z",
    "updated_at": "2015-10-27T11:24:08Z",
    "closed_at": "2015-10-27T11:24:08Z",
    "author_association": "NONE",
    "body": "I have been debugging some RPC-related shutdown hangs in bitcoin-qt on windows.  The behavior is worse in 0.8.2, but there were problems before 0.8.2 as well.\n1. In ServiceConnection, there is a loop that processes multiple requests from the same connection as long as \"Connection: close\" is not specified in the request.  During application shutdown, nothing stops that processing, so a client can continue to make requests indefinitely using an already established connection.  This is new in 0.8.2 -- in 0.8.1 there was a check for fShutdown before processing each request.\n2. If an RPC connection is blocked, for example in ReadHTTPRequestLine, shutdown can be delayed indefinitely while waiting for input from the client.  That can happen due to a misbehaving client, but it can also happen with a well-behaved client that makes multiple requests on the same connection.  After the first request and reply, we will reach ReadHTTPRequestLine and wait until the client has another request to make.  This is not new in 0.8.2.\n\nFor now I have worked around the problems by forcing ServiceConnection to close the connection after the first request in all cases.  There is still a possibility of hangs if the client fails to send the first request promptly.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2726",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2726/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2726/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2726/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2726",
    "id": 15035740,
    "number": 2726,
    "title": "erraneous InvalidChainFound messages",
    "user": {
      "login": "rebroad",
      "id": 1530283,
      "avatar_url": "https://avatars2.githubusercontent.com/u/1530283?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rebroad",
      "html_url": "https://github.com/rebroad",
      "followers_url": "https://api.github.com/users/rebroad/followers",
      "following_url": "https://api.github.com/users/rebroad/following{/other_user}",
      "gists_url": "https://api.github.com/users/rebroad/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rebroad/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rebroad/subscriptions",
      "organizations_url": "https://api.github.com/users/rebroad/orgs",
      "repos_url": "https://api.github.com/users/rebroad/repos",
      "events_url": "https://api.github.com/users/rebroad/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rebroad/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 97470796,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/UTXO%20Db%20and%20Indexes",
        "name": "UTXO Db and Indexes",
        "color": "fbca04",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 53,
    "created_at": "2013-06-02T03:21:08Z",
    "updated_at": "2015-02-18T16:20:23Z",
    "closed_at": "2015-02-18T16:20:23Z",
    "author_association": "CONTRIBUTOR",
    "body": "2013-05-31 09:28:32 Bitcoin version v0.8.2-beta (2013-05-25 08:48:25 -0700)\n2013-05-31 09:28:41 LoadBlockIndexDB(): hashBestChain=000000000000036b0687c15229f7c337265f2154c6ece7a1fde625f97c260ebf  height=197884 date=2012-09-08 19:08:11\n2013-05-31 11:05:45 SetBestChain: new best=000000000000002f6afc75f359c785e48c294a881ab5ace093ce84146f8c1f0b  height=228337  log2_work=69.636427  tx=15075580  date\n=2013-03-28 03:34:39 progress=0.487031\n2013-05-31 11:05:46 InvalidChainFound: invalid block=000000000000002a0bd37c0f44c2f35a75ede3b01f6710c0369a79dfdd4837da  height=228338  log2_work=69.636473  date=20\n13-03-28 03:38:55\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2719",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2719/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2719/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2719/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2719",
    "id": 14974391,
    "number": 2719,
    "title": "Client failure to launch. /Library/Application Support/Bitcoin does not exist",
    "user": {
      "login": "jafoal",
      "id": 4576334,
      "avatar_url": "https://avatars0.githubusercontent.com/u/4576334?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jafoal",
      "html_url": "https://github.com/jafoal",
      "followers_url": "https://api.github.com/users/jafoal/followers",
      "following_url": "https://api.github.com/users/jafoal/following{/other_user}",
      "gists_url": "https://api.github.com/users/jafoal/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jafoal/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jafoal/subscriptions",
      "organizations_url": "https://api.github.com/users/jafoal/orgs",
      "repos_url": "https://api.github.com/users/jafoal/repos",
      "events_url": "https://api.github.com/users/jafoal/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jafoal/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 234877,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
        "name": "Windows",
        "color": "884400",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 3,
    "created_at": "2013-05-31T03:27:38Z",
    "updated_at": "2014-01-10T12:12:51Z",
    "closed_at": "2014-01-10T12:12:51Z",
    "author_association": "NONE",
    "body": "After updating to 8.2 from 8.1 I can no longer start the Bitcoin-qt client. It always \"quits unexpectedly\". I tried un installing and re installing several times and with a couple of the past versions. When I tried 7.2 I could get the client to launch and the ctransactions all matched, however, I tried looking for the /Application Support/Bitcoin/ folder, and it's still missing. It seems like something is preventing the directory from being created during install..? I have my back up wallet.dat file else where and I did trying moving around but nothing seems to work.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2706",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2706/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2706/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2706/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2706",
    "id": 14903221,
    "number": 2706,
    "title": "Bitcoin-Qt debug console crash, getblocktemplate / getwork",
    "user": {
      "login": "gavinandresen",
      "id": 331997,
      "avatar_url": "https://avatars0.githubusercontent.com/u/331997?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gavinandresen",
      "html_url": "https://github.com/gavinandresen",
      "followers_url": "https://api.github.com/users/gavinandresen/followers",
      "following_url": "https://api.github.com/users/gavinandresen/following{/other_user}",
      "gists_url": "https://api.github.com/users/gavinandresen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gavinandresen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gavinandresen/subscriptions",
      "organizations_url": "https://api.github.com/users/gavinandresen/orgs",
      "repos_url": "https://api.github.com/users/gavinandresen/repos",
      "events_url": "https://api.github.com/users/gavinandresen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gavinandresen/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2013-05-29T17:53:19Z",
    "updated_at": "2013-05-31T06:00:04Z",
    "closed_at": "2013-05-31T06:00:04Z",
    "author_association": "CONTRIBUTOR",
    "body": "Calling getblocktemplate or getwork in the Bitcoin-Qt console window causes a crash with 0.8.2.\n\nThe cause is pMiningKey being uninitialized (it is initialized in StartRPCThreads(), which isn't called if Bitcoin-Qt is not running with the -server flag).\n\nWorkaround is to run Bitcoin-Qt with -server.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2704",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2704/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2704/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2704/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2704",
    "id": 14869638,
    "number": 2704,
    "title": "Recursive mutex error at close up with an unlocked encrypted wallet",
    "user": {
      "login": "rdponticelli",
      "id": 1192483,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1192483?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rdponticelli",
      "html_url": "https://github.com/rdponticelli",
      "followers_url": "https://api.github.com/users/rdponticelli/followers",
      "following_url": "https://api.github.com/users/rdponticelli/following{/other_user}",
      "gists_url": "https://api.github.com/users/rdponticelli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rdponticelli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rdponticelli/subscriptions",
      "organizations_url": "https://api.github.com/users/rdponticelli/orgs",
      "repos_url": "https://api.github.com/users/rdponticelli/repos",
      "events_url": "https://api.github.com/users/rdponticelli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rdponticelli/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": {
      "login": "laanwj",
      "id": 126646,
      "avatar_url": "https://avatars0.githubusercontent.com/u/126646?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/laanwj",
      "html_url": "https://github.com/laanwj",
      "followers_url": "https://api.github.com/users/laanwj/followers",
      "following_url": "https://api.github.com/users/laanwj/following{/other_user}",
      "gists_url": "https://api.github.com/users/laanwj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/laanwj/subscriptions",
      "organizations_url": "https://api.github.com/users/laanwj/orgs",
      "repos_url": "https://api.github.com/users/laanwj/repos",
      "events_url": "https://api.github.com/users/laanwj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/laanwj/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "laanwj",
        "id": 126646,
        "avatar_url": "https://avatars0.githubusercontent.com/u/126646?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/laanwj",
        "html_url": "https://github.com/laanwj",
        "followers_url": "https://api.github.com/users/laanwj/followers",
        "following_url": "https://api.github.com/users/laanwj/following{/other_user}",
        "gists_url": "https://api.github.com/users/laanwj/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/laanwj/subscriptions",
        "organizations_url": "https://api.github.com/users/laanwj/orgs",
        "repos_url": "https://api.github.com/users/laanwj/repos",
        "events_url": "https://api.github.com/users/laanwj/events{/privacy}",
        "received_events_url": "https://api.github.com/users/laanwj/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 5,
    "created_at": "2013-05-29T01:17:44Z",
    "updated_at": "2014-07-08T17:13:14Z",
    "closed_at": "2014-01-17T16:15:55Z",
    "author_association": "CONTRIBUTOR",
    "body": "I've seen this error twice at close up, after importing/exporting keys on wallets:\n\nbitcoin-qt: /usr/include/boost/thread/pthread/recursive_mutex.hpp:67: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.\nAborted\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2701",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2701/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2701/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2701/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2701",
    "id": 14808877,
    "number": 2701,
    "title": "bitcoin-qt St13runtime_error during exit",
    "user": {
      "login": "wtogami",
      "id": 93665,
      "avatar_url": "https://avatars1.githubusercontent.com/u/93665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wtogami",
      "html_url": "https://github.com/wtogami",
      "followers_url": "https://api.github.com/users/wtogami/followers",
      "following_url": "https://api.github.com/users/wtogami/following{/other_user}",
      "gists_url": "https://api.github.com/users/wtogami/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wtogami/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wtogami/subscriptions",
      "organizations_url": "https://api.github.com/users/wtogami/orgs",
      "repos_url": "https://api.github.com/users/wtogami/repos",
      "events_url": "https://api.github.com/users/wtogami/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wtogami/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 3,
    "created_at": "2013-05-27T19:48:47Z",
    "updated_at": "2015-05-18T09:28:07Z",
    "closed_at": "2015-05-18T09:28:07Z",
    "author_association": "CONTRIBUTOR",
    "body": "bitcoin-0.8.2-rc3 gitian x86_64\n\nhttp://togami.com/~warren/temp/wallet.dat\nwallet.dat that reproduces this issue.  This was created by kill -9 of previous bitcoin-qt after it hanged during shutdown in Issue #2690.\n\nBitcoin-Qt works properly, but during exit it crashes with this error:\n\nreceive version message: version 70001, blocks=238242, us=53.15.36.49:49450, them=188.79.149.44:8333, peer=188.79.149.44:8333\nAdded 1 addresses from 142.4.208.152: 63 tried, 14191 new\naddcon thread interrupt\nmsghand thread interrupt\ndumpaddr thread stop\nnet thread interrupt\nconnection timeout\nopencon thread interrupt\nFlush(false)\nwallet.dat refcount=0\nwallet.dat checkpoint\nwallet.dat detach\nwallet.dat closed\nDBFlush(false) ended               0ms\nStopNode()\nFlushed 14254 addresses to peers.dat  51ms\n\n---\n\nEXCEPTION: St13runtime_error  \nCDB() : can't open database file wallet.dat, error -30974  \nbitcoin in Runaway exception\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2691",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2691/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2691/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2691/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2691",
    "id": 14713280,
    "number": 2691,
    "title": "spurious missing menu",
    "user": {
      "login": "schildbach",
      "id": 743306,
      "avatar_url": "https://avatars0.githubusercontent.com/u/743306?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/schildbach",
      "html_url": "https://github.com/schildbach",
      "followers_url": "https://api.github.com/users/schildbach/followers",
      "following_url": "https://api.github.com/users/schildbach/following{/other_user}",
      "gists_url": "https://api.github.com/users/schildbach/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/schildbach/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/schildbach/subscriptions",
      "organizations_url": "https://api.github.com/users/schildbach/orgs",
      "repos_url": "https://api.github.com/users/schildbach/repos",
      "events_url": "https://api.github.com/users/schildbach/events{/privacy}",
      "received_events_url": "https://api.github.com/users/schildbach/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 135946,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/GUI",
        "name": "GUI",
        "color": "02d7e1",
        "default": false
      },
      {
        "id": 234878,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Linux/Unix",
        "name": "Linux/Unix",
        "color": "770000",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 8,
    "created_at": "2013-05-24T09:12:08Z",
    "updated_at": "2014-01-07T08:41:12Z",
    "closed_at": "2014-01-07T08:41:12Z",
    "author_association": "CONTRIBUTOR",
    "body": "Several times now I realized that bitcoin-qt is missing its menu sometimes. This is on Ubuntu 13.04, but I've also seen it on 12.10 and perhaps earlier. Its with bitcoin-qt 0.8.2rc2 (compiled myself), but I've also seen it with 0.8.1 and earlier. If this happens, the rest of the client appears to work without problems.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2667",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2667/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2667/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2667/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2667",
    "id": 14482950,
    "number": 2667,
    "title": "lockunspent returns true even for non-existent outputs",
    "user": {
      "login": "themighty1",
      "id": 555272,
      "avatar_url": "https://avatars1.githubusercontent.com/u/555272?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/themighty1",
      "html_url": "https://github.com/themighty1",
      "followers_url": "https://api.github.com/users/themighty1/followers",
      "following_url": "https://api.github.com/users/themighty1/following{/other_user}",
      "gists_url": "https://api.github.com/users/themighty1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/themighty1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/themighty1/subscriptions",
      "organizations_url": "https://api.github.com/users/themighty1/orgs",
      "repos_url": "https://api.github.com/users/themighty1/repos",
      "events_url": "https://api.github.com/users/themighty1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/themighty1/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 98279177,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/RPC/REST/ZMQ",
        "name": "RPC/REST/ZMQ",
        "color": "0052cc",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2013-05-18T12:36:14Z",
    "updated_at": "2017-11-16T11:24:38Z",
    "closed_at": "2017-11-16T11:24:38Z",
    "author_association": "NONE",
    "body": "just use lockunspent with \"txid\":123 to reproduce\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2664",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2664/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2664/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2664/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2664",
    "id": 14469039,
    "number": 2664,
    "title": "ExtractUserKey",
    "user": {
      "login": "kerzane",
      "id": 4460152,
      "avatar_url": "https://avatars2.githubusercontent.com/u/4460152?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kerzane",
      "html_url": "https://github.com/kerzane",
      "followers_url": "https://api.github.com/users/kerzane/followers",
      "following_url": "https://api.github.com/users/kerzane/following{/other_user}",
      "gists_url": "https://api.github.com/users/kerzane/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kerzane/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kerzane/subscriptions",
      "organizations_url": "https://api.github.com/users/kerzane/orgs",
      "repos_url": "https://api.github.com/users/kerzane/repos",
      "events_url": "https://api.github.com/users/kerzane/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kerzane/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 97470796,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/UTXO%20Db%20and%20Indexes",
        "name": "UTXO Db and Indexes",
        "color": "fbca04",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 21,
    "created_at": "2013-05-17T19:59:44Z",
    "updated_at": "2016-01-29T13:06:21Z",
    "closed_at": "2016-01-29T13:06:21Z",
    "author_association": "NONE",
    "body": "Initialising bitcoind on osx. Starts to load blockchain and crashes after 3573 blocks. \n\nerror message:\n\nAssertion failed: (internal_key.size() >= 8), function ExtractUserKey, file ./db/dbformat.h, line 96.\n\nsame message as in https://github.com/bitcoin/bitcoin/issues/2550\n\nno message in debug.log\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2646",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2646/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2646/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2646/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2646",
    "id": 14236099,
    "number": 2646,
    "title": "Bitcoin 0.8.2rc1 on WinXP SP3",
    "user": {
      "login": "subSTRATA",
      "id": 2906757,
      "avatar_url": "https://avatars2.githubusercontent.com/u/2906757?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/subSTRATA",
      "html_url": "https://github.com/subSTRATA",
      "followers_url": "https://api.github.com/users/subSTRATA/followers",
      "following_url": "https://api.github.com/users/subSTRATA/following{/other_user}",
      "gists_url": "https://api.github.com/users/subSTRATA/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/subSTRATA/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/subSTRATA/subscriptions",
      "organizations_url": "https://api.github.com/users/subSTRATA/orgs",
      "repos_url": "https://api.github.com/users/subSTRATA/repos",
      "events_url": "https://api.github.com/users/subSTRATA/events{/privacy}",
      "received_events_url": "https://api.github.com/users/subSTRATA/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 7,
    "created_at": "2013-05-12T15:35:22Z",
    "updated_at": "2014-01-10T11:27:18Z",
    "closed_at": "2014-01-10T11:27:18Z",
    "author_association": "NONE",
    "body": "First run:\n1. Old files removed and new archive extracted to Bitcoin install directory.\n2. Bitcoin-Qt started and synced to network, then it stucked for a while showing progress meter and acting like some blocks are missing.\n3. After a while it returned to normal state, with green check mark showing sync is complete.\n\nDebug log reveals not everything is right - an example of errors encountered, there might be more so check log file linked bellow:\n\n2013-05-12 14:32:42 received block 00000000000000a1acafe3cb63099b5cc8b5d81a0bbbf6191f5978ea05c4372c\n2013-05-12 14:32:42 Committing 30380 changed transactions to coin database...\n2013-05-12 14:32:42 \n\nEXCEPTION: St9bad_alloc\nstd::bad_alloc\nC:\\Program Files\\Bitcoin\\bitcoin-qt.exe in ProcessMessages()\n\n2013-05-12 14:32:42 ProcessMessage(block, 442684 bytes) FAILED\n\n---\n\n2013-05-12 14:36:03 ERROR: Non-canonical signature: S value excessively padded\n2013-05-12 14:36:03 ERROR: CScriptCheck() : c33bbdb11c757e9dc38063367cb460cf47d8934f8d9600c061d989b47ef2aa18 VerifySignature failed\n2013-05-12 14:36:03 ERROR: CTxMemPool::accept() : ConnectInputs failed c33bbdb11c757e9dc38063367cb460cf47d8934f8d9600c061d989b47ef2aa18\n2013-05-12 14:36:03 Misbehaving: 194.213.5.15:8333 (0 -> 0)\n\n---\n\n2013-05-12 14:30:03 ERROR: Non-canonical signature: R value excessively padded\n2013-05-12 14:30:03 ERROR: CScriptCheck() : e390b43b53d5aa15a6c76020b019eec470567a607d8de08153cd8882067d7a77 VerifySignature failed\n2013-05-12 14:30:03 ERROR: CTxMemPool::accept() : ConnectInputs failed e390b43b53d5aa15a6c76020b019eec470567a607d8de08153cd8882067d7a77\n2013-05-12 14:30:03 Misbehaving: 77.249.178.204:8333 (10 -> 10)\n\n---\n\n2013-05-12 14:31:10 ERROR: Non-canonical signature: S value negative\n2013-05-12 14:31:10 ERROR: CScriptCheck() : 1958ae3b25018b63683652f9875d1655990b5e99d22753503a00d67d56a019af VerifySignature failed\n2013-05-12 14:31:10 ERROR: CTxMemPool::accept() : ConnectInputs failed 1958ae3b25018b63683652f9875d1655990b5e99d22753503a00d67d56a019af\n2013-05-12 14:31:10 Misbehaving: 72.48.65.87:8333 (0 -> 0)\n\n---\n\n2013-05-12 14:33:05 ERROR: Non-canonical signature: R value negative\n2013-05-12 14:33:05 ERROR: CScriptCheck() : 6618eea519e01f392c48d004d81ddaea799f36ea25a6b36ed818ef021d16884c VerifySignature failed\n2013-05-12 14:33:05 ERROR: CTxMemPool::accept() : ConnectInputs failed 6618eea519e01f392c48d004d81ddaea799f36ea25a6b36ed818ef021d16884c\n2013-05-12 14:33:05 Misbehaving: 109.190.65.235:8333 (0 -> 0)\n\nClient seemed to be totally ignoring new blocks added to blockchain. I have compared block height with blockchain.info and saw that my client is 7 blocks behind but still showing green check mark. Upon exit, it crashed with error as shown on the linked image:\n\nhttp://i.imgur.com/yolpQq7.png\nFull debug log for first run: http://www.filedropper.com/debug1\n\n//////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n\nSecond run:\n1. Bitcoin-Qt started and synced properly, it updated to block height 235,845\n2. Everything looked normal until I checked log file. One node was spamming my client with ton of orphan stuff, address adds and spent inputs without ever getting even banscore 10. I find that hillarious. Here is snapshot of spamming, for more check debug log linked bellow:\n\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n2013-05-12 14:56:08 ERROR: CTxMemPool::accept() : inputs already spent\n2013-05-12 14:56:08 Misbehaving: 85.17.239.32:8333 (0 -> 0)\n\n---\n\n2013-05-12 15:01:13 Added 1 addresses from 85.17.239.32: 350 tried, 14092 new\n2013-05-12 15:01:14 Added 1 addresses from 85.17.239.32: 350 tried, 14092 new\n2013-05-12 15:01:15 Added 1 addresses from 85.17.239.32: 350 tried, 14092 new\n2013-05-12 15:01:15 Added 1 addresses from 85.17.239.32: 350 tried, 14092 new\n\nBitcoin-Qt again refused to sync with newer block which was shown on blockchain.info but it exited without any error.\n\nhttp://i.imgur.com/5vRYWkh.png (note BTC Guild self-owning, sort of :o)))\nFull debug log for second run: http://www.filedropper.com/debug2\n\nReverting to 0.8.1 for now. Let me know if you want me to test something specific.\n\nP.S. Crashes on my machine are exclussive to Bitcoin. Beside it, I have Litecoin, Terracoin, Freicon, Feathercoin, BitBar, Small Change, YACoin, Bytecoin and PPCoin clients and none of them ever crashed. Machine has 2GB RAM and 8GB fixed swap file.\n\nBitcoin-Qt reverted back to 0.8.1 and started, it was in \"attempting to sync\" mode for few minutes and then it crashed with error as shown on screenshot bellow. I'm occassionaly seeing the same or similar errors for 6+ months now, just with Bitcoin-Qt, and so far none of MS Visual C++ runtime libraries available online fixed the issue.\n\nhttp://i.imgur.com/9mFgSdY.png\nFull debug log, some weird errors inside: http://www.filedropper.com/debug3\n\nOn subsequent run Bitcoin-Qt 0.8.1 synced properly and so far everything seems normal except occassional spamming by few nodes. Syncing with newer blocks works perfectly. I'll update this post if something unexpected happens.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2639",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2639/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2639/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2639/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2639",
    "id": 14220480,
    "number": 2639,
    "title": "Signrawtransaction can throw \"TX decode failed\" even if \"decoderawtransaction\" doesn't",
    "user": {
      "login": "Sjors",
      "id": 10217,
      "avatar_url": "https://avatars1.githubusercontent.com/u/10217?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Sjors",
      "html_url": "https://github.com/Sjors",
      "followers_url": "https://api.github.com/users/Sjors/followers",
      "following_url": "https://api.github.com/users/Sjors/following{/other_user}",
      "gists_url": "https://api.github.com/users/Sjors/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Sjors/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Sjors/subscriptions",
      "organizations_url": "https://api.github.com/users/Sjors/orgs",
      "repos_url": "https://api.github.com/users/Sjors/repos",
      "events_url": "https://api.github.com/users/Sjors/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Sjors/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 6,
    "created_at": "2013-05-11T11:30:57Z",
    "updated_at": "2016-02-16T12:49:37Z",
    "closed_at": "2016-02-16T12:49:37Z",
    "author_association": "MEMBER",
    "body": "Perpaps I'm using the wrong syntax for `signrawtransaction`, but otherwise I might have found a bug.\n\nFor example this unsigned transaction gets decoded successfully (remove the line-breaks):\n\n``` bash\ncurl --user USERNAME --data-binary '{\"id\":\"t0\",\n\"method\": \"decoderawtransaction\",\n\"params\": \n[\"0100000002d354be7cd5426bfbe70517b934b8764d17ad7f93e2b8db868211851d4404740f010000001976a91423376070c7b24da64b435c71613053800494ab1c88acffffffffe49a65da5abe3edd6e5157327fe794a7c75befecaaf18fefd3154dbb4527d6d6010000001976a91423376070c7b24da64b435c71613053800494ab1c88acffffffff0240420f00000000001976a914c8a73488183dd49f63a11dea0a3b242ae70942d288ac10ae2201000000001976a91423376070c7b24da64b435c71613053800494ab1c88ac0000000001000000\"] \n}' http://127.0.0.1:8332/\n```\n\nBut when I try to sign it, it throws an exception:\n\n``` bash\ncurl --user USERNAME --data-binary '{\"id\":\"t0\",\n\"method\": \"signrawtransaction\",\n\"params\": \n[\n \"0100000002d354be7cd5426bfbe70517b934b8764d17ad7f93e2b8db868211851d4404740f010000001976a91423376070c7b24da64b435c71613053800494ab1c88acffffffffe49a65da5abe3edd6e5157327fe794a7c75befecaaf18fefd3154dbb4527d6d6010000001976a91423376070c7b24da64b435c71613053800494ab1c88acffffffff0240420f00000000001976a914c8a73488183dd49f63a11dea0a3b242ae70942d288ac10ae2201000000001976a91423376070c7b24da64b435c71613053800494ab1c88ac0000000001000000\",\n  [],\n  []\n] \n}' http://127.0.0.1:8332/\n\n{\"result\":null,\"error\":{\"code\":-22,\"message\":\"TX decode failed\"},\"id\":\"t0\"}\n```\n\nNow there might be something wrong with my transaction, but I would except `signrawtransaction` to at least throw a different error than `decoderawtransaction` if the latter successfully decodes it. \n\nLooking at the source code, the decode method does this and throws the \"TX decode failed\" message if it doesn't work:\n\n``` cpp\nCTransaction tx;\n    try {\n        ssData >> tx;\n    }\n    catch (std::exception &e) {\n        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, \"TX decode failed\");\n```\n\nThe decode method is similar but performs one extra step. My guess is that that is where the error occurs in my case, but I haven't tested this.\n\n``` cpp\nvector<CTransaction> txVariants;\n   while (!ssData.empty())\n   {\n       try {\n           CTransaction tx;\n           ssData >> tx;\n           txVariants.push_back(tx);\n```\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2631",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2631/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2631/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2631/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2631",
    "id": 14106787,
    "number": 2631,
    "title": "First time running, assertion failed",
    "user": {
      "login": "kartcl14",
      "id": 4378391,
      "avatar_url": "https://avatars3.githubusercontent.com/u/4378391?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kartcl14",
      "html_url": "https://github.com/kartcl14",
      "followers_url": "https://api.github.com/users/kartcl14/followers",
      "following_url": "https://api.github.com/users/kartcl14/following{/other_user}",
      "gists_url": "https://api.github.com/users/kartcl14/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kartcl14/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kartcl14/subscriptions",
      "organizations_url": "https://api.github.com/users/kartcl14/orgs",
      "repos_url": "https://api.github.com/users/kartcl14/repos",
      "events_url": "https://api.github.com/users/kartcl14/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kartcl14/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 97470796,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/UTXO%20Db%20and%20Indexes",
        "name": "UTXO Db and Indexes",
        "color": "fbca04",
        "default": false
      },
      {
        "id": 234877,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
        "name": "Windows",
        "color": "884400",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 7,
    "created_at": "2013-05-08T15:31:47Z",
    "updated_at": "2016-02-09T17:07:47Z",
    "closed_at": "2016-02-09T17:07:47Z",
    "author_association": "NONE",
    "body": "Hi, this is my first time running bitcoin, and it ran smoothly for a good hour or two but then it crashed. It then came up with this error and said\nSystem Error: Database Corrupted.\n![assertion failed](https://f.cloud.github.com/assets/4378391/478190/2ae2238a-b7f4-11e2-9fdd-448bf81106f9.png)\n\nCan anyone help? \n\nThanks in advanced\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2608",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2608/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2608/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2608/events",
    "html_url": "https://github.com/bitcoin/bitcoin/pull/2608",
    "id": 13900381,
    "number": 2608,
    "title": "clear path cache after getting a proper config file (fixes #2605)",
    "user": {
      "login": "jonasschnelli",
      "id": 178464,
      "avatar_url": "https://avatars3.githubusercontent.com/u/178464?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jonasschnelli",
      "html_url": "https://github.com/jonasschnelli",
      "followers_url": "https://api.github.com/users/jonasschnelli/followers",
      "following_url": "https://api.github.com/users/jonasschnelli/following{/other_user}",
      "gists_url": "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jonasschnelli/subscriptions",
      "organizations_url": "https://api.github.com/users/jonasschnelli/orgs",
      "repos_url": "https://api.github.com/users/jonasschnelli/repos",
      "events_url": "https://api.github.com/users/jonasschnelli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jonasschnelli/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/milestones/11",
      "html_url": "https://github.com/bitcoin/bitcoin/milestone/11",
      "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/milestones/11/labels",
      "id": 319469,
      "number": 11,
      "title": "v0.8.2",
      "description": null,
      "creator": {
        "login": "sipa",
        "id": 548488,
        "avatar_url": "https://avatars1.githubusercontent.com/u/548488?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sipa",
        "html_url": "https://github.com/sipa",
        "followers_url": "https://api.github.com/users/sipa/followers",
        "following_url": "https://api.github.com/users/sipa/following{/other_user}",
        "gists_url": "https://api.github.com/users/sipa/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sipa/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sipa/subscriptions",
        "organizations_url": "https://api.github.com/users/sipa/orgs",
        "repos_url": "https://api.github.com/users/sipa/repos",
        "events_url": "https://api.github.com/users/sipa/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sipa/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 0,
      "closed_issues": 28,
      "state": "closed",
      "created_at": "2013-04-23T22:57:25Z",
      "updated_at": "2013-05-24T19:41:05Z",
      "due_on": null,
      "closed_at": "2013-05-24T19:41:05Z"
    },
    "comments": 4,
    "created_at": "2013-05-02T16:58:50Z",
    "updated_at": "2014-07-12T15:53:33Z",
    "closed_at": "2013-05-03T11:52:04Z",
    "author_association": "MEMBER",
    "pull_request": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/2608",
      "html_url": "https://github.com/bitcoin/bitcoin/pull/2608",
      "diff_url": "https://github.com/bitcoin/bitcoin/pull/2608.diff",
      "patch_url": "https://github.com/bitcoin/bitcoin/pull/2608.patch"
    },
    "body": "should fix #2605, retest please.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2605",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2605/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2605/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2605/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2605",
    "id": 13897427,
    "number": 2605,
    "title": "Bitcoin-Qt using wrong data directory",
    "user": {
      "login": "gavinandresen",
      "id": 331997,
      "avatar_url": "https://avatars0.githubusercontent.com/u/331997?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gavinandresen",
      "html_url": "https://github.com/gavinandresen",
      "followers_url": "https://api.github.com/users/gavinandresen/followers",
      "following_url": "https://api.github.com/users/gavinandresen/following{/other_user}",
      "gists_url": "https://api.github.com/users/gavinandresen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gavinandresen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gavinandresen/subscriptions",
      "organizations_url": "https://api.github.com/users/gavinandresen/orgs",
      "repos_url": "https://api.github.com/users/gavinandresen/repos",
      "events_url": "https://api.github.com/users/gavinandresen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gavinandresen/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      },
      {
        "id": 135946,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/GUI",
        "name": "GUI",
        "color": "02d7e1",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": {
      "login": "laanwj",
      "id": 126646,
      "avatar_url": "https://avatars0.githubusercontent.com/u/126646?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/laanwj",
      "html_url": "https://github.com/laanwj",
      "followers_url": "https://api.github.com/users/laanwj/followers",
      "following_url": "https://api.github.com/users/laanwj/following{/other_user}",
      "gists_url": "https://api.github.com/users/laanwj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/laanwj/subscriptions",
      "organizations_url": "https://api.github.com/users/laanwj/orgs",
      "repos_url": "https://api.github.com/users/laanwj/repos",
      "events_url": "https://api.github.com/users/laanwj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/laanwj/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "laanwj",
        "id": 126646,
        "avatar_url": "https://avatars0.githubusercontent.com/u/126646?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/laanwj",
        "html_url": "https://github.com/laanwj",
        "followers_url": "https://api.github.com/users/laanwj/followers",
        "following_url": "https://api.github.com/users/laanwj/following{/other_user}",
        "gists_url": "https://api.github.com/users/laanwj/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/laanwj/subscriptions",
        "organizations_url": "https://api.github.com/users/laanwj/orgs",
        "repos_url": "https://api.github.com/users/laanwj/repos",
        "events_url": "https://api.github.com/users/laanwj/events{/privacy}",
        "received_events_url": "https://api.github.com/users/laanwj/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/milestones/11",
      "html_url": "https://github.com/bitcoin/bitcoin/milestone/11",
      "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/milestones/11/labels",
      "id": 319469,
      "number": 11,
      "title": "v0.8.2",
      "description": null,
      "creator": {
        "login": "sipa",
        "id": 548488,
        "avatar_url": "https://avatars1.githubusercontent.com/u/548488?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sipa",
        "html_url": "https://github.com/sipa",
        "followers_url": "https://api.github.com/users/sipa/followers",
        "following_url": "https://api.github.com/users/sipa/following{/other_user}",
        "gists_url": "https://api.github.com/users/sipa/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sipa/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sipa/subscriptions",
        "organizations_url": "https://api.github.com/users/sipa/orgs",
        "repos_url": "https://api.github.com/users/sipa/repos",
        "events_url": "https://api.github.com/users/sipa/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sipa/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 0,
      "closed_issues": 28,
      "state": "closed",
      "created_at": "2013-04-23T22:57:25Z",
      "updated_at": "2013-05-24T19:41:05Z",
      "due_on": null,
      "closed_at": "2013-05-24T19:41:05Z"
    },
    "comments": 4,
    "created_at": "2013-05-02T15:52:48Z",
    "updated_at": "2013-05-12T08:58:50Z",
    "closed_at": "2013-05-03T11:52:04Z",
    "author_association": "CONTRIBUTOR",
    "body": "Steps to reproduce:\n1. Create an empty data directory with a testnet bitcoin.conf; e.g.\n   mkdir /tmp/d\n   echo \"testnet=1\" >> /tmp/d/bitcoin.conf\n   echo \"rpcuser=abc\" >> /tmp/d/bitcoin.conf\n   echo \"rpcpassword=def\" >> /tmp/d/bitcoin.conf\n2. Run Bitcoin-Qt with -datadir=/tmp/d\n\nYou get a nice green splashscreen, BUT a wallet.dat and blockchain files directly in /tmp/d, not in /tmp/d/testnet3/\n\nbitcoind behaves correctly.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2597",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2597/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2597/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2597/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2597",
    "id": 13812706,
    "number": 2597,
    "title": "Small maxreceivebuffer == stuck chain",
    "user": {
      "login": "gavinandresen",
      "id": 331997,
      "avatar_url": "https://avatars0.githubusercontent.com/u/331997?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gavinandresen",
      "html_url": "https://github.com/gavinandresen",
      "followers_url": "https://api.github.com/users/gavinandresen/followers",
      "following_url": "https://api.github.com/users/gavinandresen/following{/other_user}",
      "gists_url": "https://api.github.com/users/gavinandresen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gavinandresen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gavinandresen/subscriptions",
      "organizations_url": "https://api.github.com/users/gavinandresen/orgs",
      "repos_url": "https://api.github.com/users/gavinandresen/repos",
      "events_url": "https://api.github.com/users/gavinandresen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gavinandresen/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/bitcoin/bitcoin/milestones/11",
      "html_url": "https://github.com/bitcoin/bitcoin/milestone/11",
      "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/milestones/11/labels",
      "id": 319469,
      "number": 11,
      "title": "v0.8.2",
      "description": null,
      "creator": {
        "login": "sipa",
        "id": 548488,
        "avatar_url": "https://avatars1.githubusercontent.com/u/548488?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sipa",
        "html_url": "https://github.com/sipa",
        "followers_url": "https://api.github.com/users/sipa/followers",
        "following_url": "https://api.github.com/users/sipa/following{/other_user}",
        "gists_url": "https://api.github.com/users/sipa/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sipa/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sipa/subscriptions",
        "organizations_url": "https://api.github.com/users/sipa/orgs",
        "repos_url": "https://api.github.com/users/sipa/repos",
        "events_url": "https://api.github.com/users/sipa/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sipa/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 0,
      "closed_issues": 28,
      "state": "closed",
      "created_at": "2013-04-23T22:57:25Z",
      "updated_at": "2013-05-24T19:41:05Z",
      "due_on": null,
      "closed_at": "2013-05-24T19:41:05Z"
    },
    "comments": 1,
    "created_at": "2013-04-30T15:47:37Z",
    "updated_at": "2013-05-03T22:16:23Z",
    "closed_at": "2013-05-03T22:13:49Z",
    "author_association": "CONTRIBUTOR",
    "body": "Bug reported via email, I haven't tried to reproduce:\n\nWhen You use -maxreceivebuffer=100 then You will get stuck at height #231402. It refuses to download any higher unless you take out this command switch.\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2594",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2594/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2594/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2594/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2594",
    "id": 13797974,
    "number": 2594,
    "title": "Assertion failed",
    "user": {
      "login": "AlexHeino",
      "id": 3141083,
      "avatar_url": "https://avatars3.githubusercontent.com/u/3141083?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AlexHeino",
      "html_url": "https://github.com/AlexHeino",
      "followers_url": "https://api.github.com/users/AlexHeino/followers",
      "following_url": "https://api.github.com/users/AlexHeino/following{/other_user}",
      "gists_url": "https://api.github.com/users/AlexHeino/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AlexHeino/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AlexHeino/subscriptions",
      "organizations_url": "https://api.github.com/users/AlexHeino/orgs",
      "repos_url": "https://api.github.com/users/AlexHeino/repos",
      "events_url": "https://api.github.com/users/AlexHeino/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AlexHeino/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 5,
    "created_at": "2013-04-30T09:09:57Z",
    "updated_at": "2013-05-12T09:03:14Z",
    "closed_at": "2013-05-12T09:02:46Z",
    "author_association": "NONE",
    "body": "![image](https://f.cloud.github.com/assets/3141083/443172/f5cdb720-b174-11e2-972f-4f85fea8bb8e.png)\n\nI installed bitcoin for the first time yestarday.\nWhen i started the application it immediatly started to sync with the network and everything seemed fine. I therefore proceeded and made a transaction to another account to my newly created wallet. After a while though the application suddenly crashes with that message. And now when i startup the app it crashes after a few seconds with the same error message. \nIn the bitcoin application statusbar it says reindexing blocks on disk. \nAfter receiving this error i get all kinds of errors on my machine. And when i restart windows it will try to repair the disk. \n\nWhat can i do. How can i transfer the receiving address to another wallet?\n"
  },
  {
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2593",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2593/labels{/name}",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2593/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/2593/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/2593",
    "id": 13788723,
    "number": 2593,
    "title": "RPC not listening when starting up bitcoind with new ~/.bitcoin",
    "user": {
      "login": "richardassar",
      "id": 868396,
      "avatar_url": "https://avatars1.githubusercontent.com/u/868396?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/richardassar",
      "html_url": "https://github.com/richardassar",
      "followers_url": "https://api.github.com/users/richardassar/followers",
      "following_url": "https://api.github.com/users/richardassar/following{/other_user}",
      "gists_url": "https://api.github.com/users/richardassar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/richardassar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/richardassar/subscriptions",
      "organizations_url": "https://api.github.com/users/richardassar/orgs",
      "repos_url": "https://api.github.com/users/richardassar/repos",
      "events_url": "https://api.github.com/users/richardassar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/richardassar/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2013-04-30T01:14:25Z",
    "updated_at": "2015-05-18T09:14:20Z",
    "closed_at": "2015-05-18T09:14:20Z",
    "author_association": "NONE",
    "body": "On current master branch.\n\nSteps to recreate:\n\n1) run `bitcoind -daemon -debug`\n2) create the bitcoin.config file as requested\n\nOR\n\n1) copy a bitcoin.conf into ~/.bitcoin\n\n...\n\n3) start bitcoind with above parameters\n4) issue an RPC `stop` command \n\nResult is: `error: couldn't connect to server`\n\nServer killed, no mention of RPC upon inspecting the logs\n\nI've checked down to 33029bcedd982f80f7e380bff586f3ab644decce with no luck.\n\nInterestingly this is _not_ happening with `-testnet`\n\nA checkout of current master will reproduce the bug but can post logs if necessary.\n"
  }
]
